version: '2.2'
services:
  api:
    image: maciafranciele/springbootapi
    ports:
      - "8080:8080"
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: silviofernandesjr/mysql-image2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin



